[package]
name = "group"
version = "0.1.0"
edition = "2024"

[dependencies]

[lib]
path = "lib.rs"

[[bench]]
name = "ct"
harness = false

[[bench]]
name = "rt"
harness = false

[dev-dependencies]
criterion = "0.5.1"
